name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true
        type: 'string'
      create_tag:
        description: 'Create a tag'
        required: true
        type: 'boolean'

concurrency:
  group: gradle-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract tag name from workflow_dispatch
        run: echo "TAG_NAME=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      
      - name: Post tag name
        run: echo ${{ env.TAG_NAME }}
      
      - name: Update version file
        run: sed -i "s/version=.*/version=${{ env.TAG_NAME }}/g" version.txt
      
      - name: Show file
        run: cat version.txt

      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: Version file
          path: version.txt

      - name: Create tag
        if: ${{ github.event.inputs.create_tag }}
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.TAG_NAME }}
          name: v${{ env.TAG_NAME }}
          body: |
            Release ${{ env.TAG_NAME }}
          draft: true
          artifacts: version.txt
          