name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true
        type: 'string'
      create_tag:
        description: 'Create a tag'
        required: true
        default: true
        type: 'boolean'

concurrency:
  group: gradle-release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Post tag name
        run: echo ${{ github.event.inputs.version }}
      
      - name: Update version file
        run: sed -i "s/version=.*/version=${{ github.event.inputs.version }}/g" version.txt
      
      - name: Show file
        run: cat version.txt

      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: version_file
          path: version.txt

      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: mix
          path: |
            version.txt
            README.md

  release:
    runs-on: ubuntu-latest
    needs: prepare
    timeout-minutes: 4 
    if: ${{ github.event.inputs.create_tag == 'true' }}
    steps:

      - name: Download version.txt
        uses: actions/download-artifact@v4
        with:
          name: version_file
          path: .

      - name: Create tmp directory
        run: |
          mkdir out
          mkdir out/mix

      - name: Download mix
        uses: actions/download-artifact@v4
        with:
          name: mix
          path: ./out/mix/
      
      - name: Show files
        run: ls -al

      - name: Zip archive
        run: |
          cd ./out/mix/
          zip -r -v ../../mix.zip ./
          cd ../../
      
      - name: Show files
        run: ls -al
      
      - name: Show file
        run: cat version.txt

      - name: Create tag
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          body: |
            Release version ${{ github.event.inputs.version }}
          draft: true
          commit: ${{ github.sha }}
          artifacts: |
            version.txt
            mix.zip
